/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salud;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import static salud.Receta.numenf;

/**
 *
 * @author iTzFiliSalsa
 */
public class Inventario extends javax.swing.JFrame {

    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        diagnostico = new javax.swing.JComboBox();
        buscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JComboBox();
        existencias = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        disponibilidad = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        actualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JSpinner1 = new javax.swing.JSpinner();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("INVENTARIO");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Secre.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_seguro_popular.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Medicamentos por diagnostico"));

        jLabel4.setText("Diagnostico");

        diagnostico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PREVENCIÓN DE CARIES DENTAL", "DIAGNÓSTICO Y TRATAMIENTO DE SARAMPIÓN, RUBÉOLA Y PAROTIDITIS", "DIAGNÓSTICO Y TRATAMIENTO DEL DENGUE NO GRAVE (Y OTRAS FIEBRES PRODUCIDAS POR FLAVIVIRUS Y ARBOVIRUS)", "DIAGNÓSTICO Y TRATAMIENTO DE INFLUENZA", "DIAGNÓSTICO Y TRATAMIENTO DE FARINGOAMIGDALITIS AGUDA", "DIAGNÓSTICO Y TRATAMIENTO DE TOS FERINA", "DIAGNÓSTICO Y TRATAMIENTO DE RINOFARINGITIS AGUDA", "DIAGNÓSTICO Y TRATAMIENTO DE LARINGOTRAQUEITIS AGUDA", "DIAGNÓSTICO Y TRATAMIENTO DE SINUSITIS AGUDA", "DIAGNÓSTICO Y TRATAMIENTO DE CONJUNTIVITIS", "DIAGNÓSTICO Y TRATAMIENTO DEL SÍNDROME DIARREICO AGUDO", "DIAGNÓSTICO Y TRATAMIENTO DE FIEBRE PARATIFOIDEA Y OTRAS SALMONELOSIS", "DIAGNÓSTICO Y TRATAMIENTO DE DIABETES MELLITUS TIPO 1", "DIAGNÓSTICO Y TRATAMIENTO DE DIABETES MELLITUS TIPO 2", "DIAGNÓSTICO Y TRATAMIENTO INTEGRAL DE HIPERTENSIÓN ARTERIAL", " " }));
        diagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosticoActionPerformed(evt);
            }
        });

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(diagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buscar)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(diagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Existencias"));

        jLabel5.setText("Medicamento");

        nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre1ActionPerformed(evt);
            }
        });

        existencias.setText("Verificar existencias");
        existencias.setEnabled(false);
        existencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existenciasActionPerformed(evt);
            }
        });

        jLabel6.setText("Existencias:");

        disponibilidad.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        disponibilidad.setText("0 ");

        jLabel9.setText("Presentacion");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(nombre2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(existencias)
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(disponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(existencias)
                    .addComponent(jLabel6)
                    .addComponent(disponibilidad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Actualizar"));

        jLabel8.setText("Agregar");

        actualizar.setText("Actualizar");
        actualizar.setEnabled(false);
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        jLabel7.setText("Ingrese solamente la cantidad a agregar");

        jLabel10.setText("no el numero de medicamentos en el");

        jLabel11.setText("inventario");

        JSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        JSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JSpinner1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        JSpinner1.setEditor(new javax.swing.JSpinner.NumberEditor(JSpinner1, ""));
        JSpinner1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(JSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(actualizar))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel10))
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(actualizar)
                    .addComponent(JSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(215, 215, 215)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosticoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_diagnosticoActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        String diagnostic;
        diagnostic=(String)diagnostico.getSelectedItem();
        if(diagnostic=="PREVENCIÓN DE CARIES DENTAL"){
            nombre1.removeAllItems();
            nombre1.addItem("FLUORURO DE SODIO");
        }
        if(diagnostic=="DIAGNÓSTICO Y TRATAMIENTO DE SARAMPIÓN, RUBÉOLA Y PAROTIDITIS"){
            nombre1.removeAllItems();
            nombre1.addItem("NAPROXENO");
            nombre1.addItem("PARACETAMOL");
            nombre1.addItem("VITAMINAS A, C, D"); 
        }
        if(diagnostic=="DIAGNÓSTICO Y TRATAMIENTO DEL DENGUE NO GRAVE (Y OTRAS FIEBRES PRODUCIDAS POR FLAVIVIRUS Y ARBOVIRUS)"){
            nombre1.removeAllItems();
            nombre1.addItem("ELECTROLITOS");
            nombre1.addItem("PARACETAMOL");
        }
        if(diagnostic=="DIAGNÓSTICO Y TRATAMIENTO DE INFLUENZA"){
            nombre1.removeAllItems();
            nombre1.addItem("METAMIZOL SÓDICO");
            nombre1.addItem("OSELTAMIVIR");
            nombre1.addItem("PARACETAMOL");
        }
        if(diagnostic=="DIAGNÓSTICO Y TRATAMIENTO DE FARINGOAMIGDALITIS AGUDA"){
            nombre1.removeAllItems();
            nombre1.addItem("AMOXICILINA ÁCIDO CLAVULÁNICO");
            nombre1.addItem("AMPICILINA");
            nombre1.addItem("BENCILPENICILINA BENZATICA COMPUESTA");
            nombre1.addItem("BENCILPENICILINA PROCAINICA CON CRISTALINA");
            nombre1.addItem("BENZATINA BENCILPENICILINA");
            nombre1.addItem("ERITROMICINA");
            nombre1.addItem("TRIMETOPRIMASULFAMETOXAZOL");
            nombre1.addItem("NAPROXENO");
            nombre1.addItem("PARACETAMOL");
        }
        if(diagnostic=="DIAGNÓSTICO Y TRATAMIENTO DE TOS FERINA"){
            nombre1.removeAllItems();
            nombre1.addItem("ERITROMICINA");
            nombre1.addItem("NAPROXENO");
            nombre1.addItem("PARACETAMOL");
        }
        if(diagnostic=="DIAGNÓSTICO Y TRATAMIENTO DE TOS FERINA"){
            nombre1.removeAllItems();
            nombre1.addItem("ERITROMICINA");
            nombre1.addItem("NAPROXENO");
            nombre1.addItem("PARACETAMOL");
        }
        if(diagnostic=="DIAGNÓSTICO Y TRATAMIENTO DE RINOFARINGITIS AGUDA"){
            nombre1.removeAllItems();
            nombre1.addItem("CLORFENAMINA");
            nombre1.addItem("LORATADINA");
            nombre1.addItem("METAMIZOL SÓDICO");
            nombre1.addItem("PARACETAMOL");
        }
        if(diagnostic=="DIAGNÓSTICO Y TRATAMIENTO DE LARINGOTRAQUEITIS AGUDA"){
            nombre1.removeAllItems();
            nombre1.addItem("METAMIZOL SÓDICO ");
            nombre1.addItem("NAPROXENO ");
            nombre1.addItem("PARACETAMOL");
        }
        if(diagnostic=="DIAGNÓSTICO Y TRATAMIENTO DE SINUSITIS AGUDA"){
            
            nombre1.removeAllItems();nombre1.addItem("AMOXICILINA ÁCIDO CLAVULÁNICO");
            nombre1.addItem("AMOXICILINA");
            nombre1.addItem("CEFALEXINA");
            nombre1.addItem("CIPROFLOXACINO");
            nombre1.addItem("DICLOFENACO");
            nombre1.addItem("ERITROMICINA");
            nombre1.addItem("LORATADINA");
            nombre1.addItem("METAMIZOL SÓDICO");
            nombre1.addItem("NAPROXENO");
            nombre1.addItem("PARACETAMOL");
            nombre1.addItem("TRIMETOPRIMASULFAMETOXAZOL");
        }
        if(diagnostic=="DIAGNÓSTICO Y TRATAMIENTO DE CONJUNTIVITIS"){
            nombre1.removeAllItems();
            nombre1.addItem("ACICLOVIR");
            nombre1.addItem("CLORANFENICOL");
            nombre1.addItem("CLORURO DE SODIO");
            nombre1.addItem("NAFAZOLINA");
            nombre1.addItem("NEOMICINA, POLIMIXINA B Y GRAMICIDINA");
            nombre1.addItem("PREDNISOLONA");
            nombre1.addItem("PREDNISOLONA-SULFACETAMIDA");
            nombre1.addItem("SULFACETAMIDA");
            nombre1.addItem("TETRACAÍNA");
            nombre1.addItem("TOBRAMICINA");
        }
        if(diagnostic=="DIAGNÓSTICO Y TRATAMIENTO DEL SÍNDROME DIARREICO AGUDO"){
            nombre1.removeAllItems();
            nombre1.addItem("BUTILHIOSCINA");
            nombre1.addItem("BUTILHIOSCINA-METAMIZOL");
            nombre1.addItem("DOXICICLINA");
            nombre1.addItem("ELECTROLITOS");
            nombre1.addItem("ERITROMICINA ");
            nombre1.addItem("FOSFATO DE POTASIO");
            nombre1.addItem("METAMIZOL SÓDICO ");
            nombre1.addItem("METRONIDAZOL");
            nombre1.addItem("NITAZOXANIDA");
            nombre1.addItem("PARACETAMOL");
            nombre1.addItem("TETRACICLINA");
            nombre1.addItem("TRIMETOPRIMASULFAMETOXAZOL");
        }
        if(diagnostic=="DIAGNÓSTICO Y TRATAMIENTO DE FIEBRE PARATIFOIDEA Y OTRAS SALMONELOSIS"){
            nombre1.removeAllItems();
            nombre1.addItem("AMOXICILINA");
            nombre1.addItem("BUTILHIOSCINA ");
            nombre1.addItem("CIPROFLOXACINO");
            nombre1.addItem("CLORANFENICOL ");
            nombre1.addItem("ELECTROLITOS");
            nombre1.addItem("METAMIZOL SÓDICO");
            nombre1.addItem("PARACETAMOL");
            nombre1.addItem("TRIMETOPRIMASULFAMETOXAZOL");
        }
        if(diagnostic=="DIAGNÓSTICO Y TRATAMIENTO DE DIABETES MELLITUS TIPO 1"){
            nombre1.removeAllItems();
            nombre1.addItem("INSULINA ASPARTICA");
            nombre1.addItem("INSULINA DEMETIR");
            nombre1.addItem("INSULINA GLARGINA");
            nombre1.addItem("INSULINA HUMANA");
            nombre1.addItem("INSULINA LISPRO");
            nombre1.addItem("INSULINA LISPRO PROTAMINA");
        }
        if(diagnostic=="DIAGNÓSTICO Y TRATAMIENTO DE DIABETES MELLITUS TIPO 2"){
            nombre1.removeAllItems();
            nombre1.addItem("GLIBENCLAMIDA");
            nombre1.addItem("INSULINA ASPARTICA");
            nombre1.addItem("INSULINA DEMETIR");
            nombre1.addItem("INSULINA GLARGINA");
            nombre1.addItem("INSULINA HUMANA");
            nombre1.addItem("INSULINA LISPRO");
            nombre1.addItem("INSULINA LISPRO PROTAMINA");
            nombre1.addItem("LINAGLIPTINA");
            nombre1.addItem("METFORMINA");
            nombre1.addItem("SITAGLIPTINA");
            nombre1.addItem("VILDAGLIPTINA");
        }
        if(diagnostic=="DIAGNÓSTICO Y TRATAMIENTO INTEGRAL DE HIPERTENSIÓN ARTERIAL"){
            nombre1.removeAllItems();
            nombre1.addItem("ÁCIDO ACETILSALICÍLICO");
            nombre1.addItem("AMLODIPINO");
            nombre1.addItem("CANDESARTÁN CILEXETILO HIDROCLOROTIAZIDA");
            nombre1.addItem("CAPTOPRIL");
            nombre1.addItem("CLORTALIDONA");
            nombre1.addItem("ENALAPRIL O LISINOPRIL O RAMIPRIL");
            nombre1.addItem("ESMOLOL");
            nombre1.addItem("FUROSEMIDA");
            nombre1.addItem("HIDROCLOROTIAZIDA");
            nombre1.addItem("IRBESARTÁN");
            nombre1.addItem("ISOSORBIDA");
            nombre1.addItem("LOSARTÁN");
            nombre1.addItem("METOPROLOL");
            nombre1.addItem("NIFEDIPINO");
            nombre1.addItem("NITROPRUSIATO");
            nombre1.addItem("PROPRANOLOL");
            nombre1.addItem("TELMISARTÁN");
            nombre1.addItem("TELMISARTÁN HIDROCLOROTIAZIDA");
            nombre1.addItem("TRINITRATO DE GLICERILO");
            nombre1.addItem("VERAPAMILO");
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void existenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existenciasActionPerformed
        // TODO add your handling code here:
        try{
                            String enfermedad1=(String)nombre1.getSelectedItem();
                        String subenfermedad1=(String)nombre2.getSelectedItem();
                        File f = new File("src\\"+enfermedad1+"\\"+subenfermedad1+".txt");
                        if(f.exists()){
                            FileReader fr = new FileReader(f);
                            BufferedReader br = new BufferedReader(fr);
                            String linea;
                            linea = br.readLine();
                            numenf=Integer.parseInt(linea);
                            if(numenf==0){
                                disponibilidad.setForeground(Color.red);
                                JOptionPane.showMessageDialog(this, "No hay existencias, se recomienda actualizar el inventario");
                            }else{
                                disponibilidad.setForeground(Color.BLACK);
                            }
                            
                            disponibilidad.setText(""+numenf);
                            br.close();
                            actualizar.setEnabled(true);
                    }
        }catch(Exception e){}
        
    }//GEN-LAST:event_existenciasActionPerformed

    private void nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre1ActionPerformed
        // TODO add your handling code here:
        if(nombre1.getSelectedItem()=="DICLOFENACO"){
            nombre2.removeAllItems();
            nombre2.addItem("CAPSULA DICLOFENACO");
            nombre2.addItem("INYECTABLE DICLOFENACO");
        }
        if(nombre1.getSelectedItem()=="CIPROFLOXACINO"){
            nombre2.removeAllItems();
            nombre2.addItem("TABLETA CIPROFLOXACINO");
        }
        if(nombre1.getSelectedItem()=="CEFALEXINA"){
            nombre2.removeAllItems();
            nombre2.addItem("TABLETA CEFALEXINA");
        }
        if(nombre1.getSelectedItem()=="AMOXICILINA"){
            nombre2.removeAllItems();
            nombre2.addItem("12 CAPSULAS AMOXICILINA");
            nombre2.addItem("15 CAPSULAS AMOXICILINA");
            nombre2.addItem("AMOXICILINA SUSPENSION ORAL");
        }
        if(nombre1.getSelectedItem()=="NAPROXENO "){
            nombre2.removeAllItems();
            nombre2.addItem("SUSPENSION ORAL NAPROXENO");
            nombre2.addItem("INYECTABLE NAPROXENO");
        }
        if(nombre1.getSelectedItem()=="METAMIZOL SÓDICO "){
            nombre2.removeAllItems();
            nombre2.addItem("METAMIZOL COMPRIMIDO");
            nombre2.addItem("METAMIZOL INYECTABLE");
        }
        if(nombre1.getSelectedItem()=="CLORFENAMINA"){
            nombre2.removeAllItems();
            nombre2.addItem("JARABE CLORFENAMINA");
            nombre2.addItem("TABLETA CLORFENAMINA");
        }
        if(nombre1.getSelectedItem()=="LORATADINA"){
            nombre2.removeAllItems();
            nombre2.addItem("JARABE LORATADINA");
            nombre2.addItem("TABLETA LORATADINA");
        }
        if(nombre1.getSelectedItem()=="FLUORURO DE SODIO"){
            nombre2.removeAllItems();
            nombre2.addItem("FLUORURO DE SODIO");
        }
        if(nombre1.getSelectedItem()=="NAPROXENO"){
            nombre2.removeAllItems();
            nombre2.addItem("SUSPENSION ORAL NAPROXENO");
            nombre2.addItem("NAPROXENO TABLETA");
        }
        if(nombre1.getSelectedItem()=="PARACETAMOL"){
            nombre2.removeAllItems();
            nombre2.addItem("PARACETAMOL TABLETA");
             nombre2.addItem("SOLUCION ORAL PARACETAMOL");
            nombre2.addItem("3 SUPOSITORIOS 300 mg");
            nombre2.addItem("3 SUPOSITORIOS 100 mg");
            nombre2.addItem("6 SUPOSITORIOS 100 mg");
            nombre2.addItem("10 SUPOSITORIOS 100 mg");
        }
        if(nombre1.getSelectedItem()=="VITAMINAS A, C, D"){
            nombre2.removeAllItems();
            nombre2.addItem("VITAMINAS A, C, D");
        }
        if(nombre1.getSelectedItem()=="ELECTROLITOS"){
            nombre2.removeAllItems();
            nombre2.addItem("ELECTROLITOS ORALES");
        }
        if(nombre1.getSelectedItem()=="METAMIZOL SÓDICO"){
            nombre2.removeAllItems();
            nombre2.addItem("METAMIZOL COMPRIMIDO");
        }
        if(nombre1.getSelectedItem()=="OSELTAMIVIR"){
            nombre2.removeAllItems();
            nombre2.addItem("OSELTAMIVIR CAPSULA");
        }
        if(nombre1.getSelectedItem()=="AMOXICILINA ÁCIDO CLAVULÁNICO"){
            nombre2.removeAllItems();
            nombre2.addItem("SUSPENSIÓN ORAL AMOXICILINA");
            nombre2.addItem("TABLETA AMOXICILINA");
        }
        if(nombre1.getSelectedItem()=="AMPICILINA"){
            nombre2.removeAllItems();
            nombre2.addItem("SUSPENSIÓN ORAL AMPICILINA");
        }
        if(nombre1.getSelectedItem()=="BENCILPENICILINA BENZATICA COMPUESTA"){
            nombre2.removeAllItems();
            nombre2.addItem("SUSPENSIÓN INYECTABLE BENCILPENICILINA");
        }
        if(nombre1.getSelectedItem()=="BENCILPENICILINA PROCAINICA CON CRISTALINA"){
            nombre2.removeAllItems();
            nombre2.addItem("3ml INYECTABLE");
            nombre2.addItem("2ml INYECTABLE");
        }
        if(nombre1.getSelectedItem()=="BENZATINA BENCILPENICILINA"){
            nombre2.removeAllItems();
            nombre2.addItem("BENZATINA INYECTABLE");
        }
        if(nombre1.getSelectedItem()=="ERITROMICINA "){
            nombre2.removeAllItems();
            nombre2.addItem("ERITROMICINA ORAL");
        }
        if(nombre1.getSelectedItem()=="ERITROMICINA"){
            nombre2.removeAllItems();
            nombre2.addItem("ERITROMICINA CAPSULA");
            nombre2.addItem("ERITROMICINA ORAL");
        }
        if(nombre1.getSelectedItem()=="TRIMETOPRIMASULFAMETOXAZOL"){
            nombre2.removeAllItems();
            nombre2.addItem("TABLETA TRIME");
            nombre2.addItem("ORAL TRIME");
        }
        if(nombre1.getSelectedItem()=="TOBRAMICINA"){
            nombre2.removeAllItems();
            nombre2.addItem("SOLUCION OFTAMOLICA TOBRAMICINA");
        }
        if(nombre1.getSelectedItem()=="TETRACAÍNA"){
            nombre2.removeAllItems();
            nombre2.addItem("SOLUCION OFTAMOLICA TETRACAÍNA");
        }
        if(nombre1.getSelectedItem()=="SULFACETAMIDA"){
            nombre2.removeAllItems();
            nombre2.addItem("SOLUCION OFTAMOLICA SULFACETAMIDA");
        }
        if(nombre1.getSelectedItem()=="PREDNISOLONA-SULFACETAMIDA"){
            nombre2.removeAllItems();
            nombre2.addItem("SUSPENSION OFTAMOLICA PREDNISOLONA");
        }
        if(nombre1.getSelectedItem()=="PREDNISOLONA"){
            nombre2.removeAllItems();
            nombre2.addItem("SOLUCION OFTAMOLICA PREDNISOLONA");
            nombre2.addItem("UNGUENTO OFTAMOLICO PREDNISOLONA");
        }
        if(nombre1.getSelectedItem()=="NEOMICINA, POLIMIXINA B Y GRAMICIDINA"){
            nombre2.removeAllItems();
            nombre2.addItem("SOLUCION OFTAMOLICA NEOMICINA");
        }
        if(nombre1.getSelectedItem()=="NAFAZOLINA"){
            nombre2.removeAllItems();
            nombre2.addItem("SOLUCION OFTAMOLICA NAFAZOLINA");
        }
        if(nombre1.getSelectedItem()=="CLORURO DE SODIO"){
            nombre2.removeAllItems();
            nombre2.addItem("POMADA CLORURO DE SODIO");
        }
        if(nombre1.getSelectedItem()=="CLORANFENICOL "){
            nombre2.removeAllItems();
            nombre2.addItem("CAPSULA CLORANFENICOL");
        }
        if(nombre1.getSelectedItem()=="CLORANFENICOL"){
            nombre2.removeAllItems();
            nombre2.addItem("SOLUCIÓN OFTAMOLICA CLORANFENICOL");
        }
        if(nombre1.getSelectedItem()=="ACICLOVIR"){
            nombre2.removeAllItems();
            nombre2.addItem("UNGUENTO OFTAMOLICO ACICLOVIR");
        }
        if(nombre1.getSelectedItem()=="TETRACICLINA"){
            nombre2.removeAllItems();
            nombre2.addItem("TABLETA TETRACICLINA");
        }
        if(nombre1.getSelectedItem()=="NITAZOXANIDA"){
            nombre2.removeAllItems();
            nombre2.addItem("SUSPENSION ORAL NITAZOXANIDA");
            nombre2.addItem("TABLETA NITAZOXANIDA");
        }
        if(nombre1.getSelectedItem()=="METRONIDAZOL"){
            nombre2.removeAllItems();
            nombre2.addItem("SUSPENSION ORAL METRONIDAZOL");
            nombre2.addItem("20 TABLETAS METRONIDAZOL");
            nombre2.addItem("30 TABLETAS METRONIDAZOL");
        }
        if(nombre1.getSelectedItem()=="ELECTROLITOS"){
            nombre2.removeAllItems();
            nombre2.addItem("POLVO ELECTROLITOS ORALES");
            nombre2.addItem("SOLUCION ELECTROLITOS ORALES");
        }
        if(nombre1.getSelectedItem()=="DOXICILINA"){
            nombre2.removeAllItems();
            nombre2.addItem("CAPSULA O TABLETA DOXICILINA");
        }
        if(nombre1.getSelectedItem()=="BUTILHIOSCINA-METAMIZOL"){
            nombre2.removeAllItems();
            nombre2.addItem("SOLUCION INYECTABLE BM");
        }
        if(nombre1.getSelectedItem()=="BUTILHIOSCINA "){
            nombre2.removeAllItems();
            nombre2.addItem("GRAGEA O TABLETA BUTILHIOSCINA");
        }
        if(nombre1.getSelectedItem()=="BUTILHIOSCINA"){
            nombre2.removeAllItems();
            nombre2.addItem("GRAGEA O TABLETA BUTILHIOSCINA");
            nombre2.addItem("SOLUCION INYECTABLE BUTILHIOSCINA");
        }
        if(nombre1.getSelectedItem()=="FOSFATO DE POTASIO"){
            nombre2.removeAllItems();
            nombre2.addItem("SOLUCION INYECTABLE FOSFATO");
        }
        if(nombre1.getSelectedItem()=="DOXICICLINA"){
            nombre2.removeAllItems();
            nombre2.addItem("CAPSULA O TABLETA DOXICILINA");
        }
        if(nombre1.getSelectedItem()=="INSULINA LISPRO PROTAMINA"){
            nombre2.removeAllItems();
            nombre2.addItem("INYECTABLE LISPRO PROTAMINA");
        }
        if(nombre1.getSelectedItem()=="INSULINA LISPRO"){
            nombre2.removeAllItems();
            nombre2.addItem("INYECTABLE LISPRO");
        }
        if(nombre1.getSelectedItem()=="INSULINA HUMANA"){
            nombre2.removeAllItems();
            nombre2.addItem("5ml INYECTABLE ACCION RAPIDA");
            nombre2.addItem("10ml INYECTABLE ACCION RAPIDA");
            nombre2.addItem("10ml INYECTABLE ACCION LENTA");
            nombre2.addItem("5ml INYECTABLE ACCION INTERMEDIA");
            nombre2.addItem("10ml INYECTABLE ACCION INTERMEDIA");
        }
        if(nombre1.getSelectedItem()=="INSULINA GLARGINA"){
            nombre2.removeAllItems();
            nombre2.addItem("10ml INYECTABLE GLARGINA");
            nombre2.addItem("3ml INYECTABLE GLARGINA");
        }
        if(nombre1.getSelectedItem()=="INSULINA DEMETIR"){
            nombre2.removeAllItems();
            nombre2.addItem("1 PLUMA INYECTABLE");
            nombre2.addItem("5 PLUMAS INYECTABLES");
        }
        if(nombre1.getSelectedItem()=="INSULINA ASPARTICA"){
            nombre2.removeAllItems();
            nombre2.addItem("INYECTABLE INSULINA*");
            nombre2.addItem("INYECTABLE INSULINA");
        }
        if(nombre1.getSelectedItem()=="VILDAGLIPTINA"){
            nombre2.removeAllItems();
            nombre2.addItem("VILDAGLIPTINA COMPRIMIDO");
        }
        if(nombre1.getSelectedItem()=="SITAGLIPTINA"){
            nombre2.removeAllItems();
            nombre2.addItem("14 COMPRIMIDOS SITAGLIPTINA");
            nombre2.addItem("28 COMPRIMIDOS SITAGLIPTINA");
        }
        if(nombre1.getSelectedItem()=="METFORMINA"){
            nombre2.removeAllItems();
            nombre2.addItem("TABLETA METFORMINA");
        }
        if(nombre1.getSelectedItem()=="LINAGLIPTINA"){
            nombre2.removeAllItems();
            nombre2.addItem("TABLETA LINAGLIPTINA");
        }
        if(nombre1.getSelectedItem()=="GLIBENCLAMIDA"){
            nombre2.removeAllItems();
            nombre2.addItem("TABLETA GLIBENCLAMIDA");
        }
         if(nombre1.getSelectedItem()=="VERAPAMILO"){
            nombre2.removeAllItems();
            nombre2.addItem("GRAGEA O TABLETA RECUBIERTA VERAPAMILO");
            nombre2.addItem("SOLUCION INYECTABLE VERAPAMILO");
        }
        if(nombre1.getSelectedItem()=="TRINITRATO DE GLICERILO"){
            nombre2.removeAllItems();
            nombre2.addItem("PARCHE TRINITRATO DE GLICERILO");
        }
        if(nombre1.getSelectedItem()=="TELMISARTÁN"){
            nombre2.removeAllItems();
            nombre2.addItem("TABLETA TELMISARTAN");
        }
        if(nombre1.getSelectedItem()=="TELMISARTÁN HIDROCLOROTIAZIDA"){
            nombre2.removeAllItems();
            nombre2.addItem("TABLETA TELMISARTANH");
        }
        if(nombre1.getSelectedItem()=="PROPRANOLOL"){
            nombre2.removeAllItems();
            nombre2.addItem("40mg TABLETA PROPRANOLOL");
            nombre2.addItem("10mg TABLETA PROPRANOLOL");
        }
        if(nombre1.getSelectedItem()=="NITROPRUSIATO"){
            nombre2.removeAllItems();
            nombre2.addItem("SOLUCION INYECTABLE NITROPRUSIATO");
        }
        if(nombre1.getSelectedItem()=="NIFEDIPINO"){
            nombre2.removeAllItems();
            nombre2.addItem("CAPSULA DE GELATINA BLANDA");
            nombre2.addItem("COMPRIMIDO DE LIBERACION PROLONGADA");
        }
        if(nombre1.getSelectedItem()=="METOPROLOL"){
            nombre2.removeAllItems();
            nombre2.addItem("TABLETA METOPROLOL");
        }
        if(nombre1.getSelectedItem()=="LOSARTÁN"){
            nombre2.removeAllItems();
            nombre2.addItem("GRAGEA LOSARTÁN");
        }
        if(nombre1.getSelectedItem()=="ISOSORBIDA"){
            nombre2.removeAllItems();
            nombre2.addItem("TABLETA ISOSORBIDA");
            nombre2.addItem("TABLETA SUBLINGUAL ISOSORBIDA");
        }
        if(nombre1.getSelectedItem()=="IRBESARTÁN"){
            nombre2.removeAllItems();
            nombre2.addItem("150mg TABLETA IRBESARTÁN");
            nombre2.addItem("300mg TABLETA IRBESARTÁN");
        }
        if(nombre1.getSelectedItem()=="HIDROCLOROTIAZIDA"){
            nombre2.removeAllItems();
            nombre2.addItem("TABLETA HIDROCLOROTIAZIDA");
        }
        if(nombre1.getSelectedItem()=="FUROSEMIDA"){
            nombre2.removeAllItems();
            nombre2.addItem("INYECTABLE FUROSEMIDA");
            nombre2.addItem("TABLETA FIROSEMIDA");
        }
        if(nombre1.getSelectedItem()=="ESMOLOL"){
            nombre2.removeAllItems();
            nombre2.addItem("INYECTABLE ESMOLOL");
        }
        if(nombre1.getSelectedItem()=="ENALAPRIL O LISINOPRIL O RAMIPRIL"){
            nombre2.removeAllItems();
            nombre2.addItem("TABLETA ENALAPRIL");
        }
        if(nombre1.getSelectedItem()=="CLORTALIDONA"){
            nombre2.removeAllItems();
            nombre2.addItem("TABLETA CLORTALIDONA");
        }
        if(nombre1.getSelectedItem()=="CAPTOPRIL"){
            nombre2.removeAllItems();
            nombre2.addItem("TABLETA CAPTOPRIL");
        }
        if(nombre1.getSelectedItem()=="CANDESARTÁN CILEXETILO HIDROCLOROTIAZIDA"){
            nombre2.removeAllItems();
            nombre2.addItem("TABLETA CANDESARTAN");
        }
        if(nombre1.getSelectedItem()=="AMLODIPINO"){
            nombre2.removeAllItems();
            nombre2.addItem("TABLETA O CAPSULA AMLODIPINO");
        }
        if(nombre1.getSelectedItem()=="ÁCIDO ACETILSALICÍLICO"){
            nombre2.removeAllItems();
            nombre2.addItem("TABLETA SOLUBLE ACELTILSALICILICO");
        }
        if(nombre1.getSelectedItem()!=null){
            existencias.setEnabled(true);
        }
    }//GEN-LAST:event_nombre1ActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        try{    
            File f = new File("src\\"+(String)nombre1.getSelectedItem()+"\\"+(String)nombre2.getSelectedItem()+".txt");
            f.delete();
            f.createNewFile();
            FileWriter fw = new FileWriter(f, true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            bw.write("");
            int valor=(int)JSpinner1.getValue();
            int ban=valor+numenf;
            pw.print((numenf+valor)+"");
            pw.close();
            disponibilidad.setText(ban+"");
            JOptionPane.showMessageDialog(this, "Medicamento actualizado con exito. Existencias: "+ban);
            numenf=0;
        }catch(Exception e){} 
    }//GEN-LAST:event_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner JSpinner1;
    private javax.swing.JButton actualizar;
    private javax.swing.JButton buscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox diagnostico;
    private javax.swing.JLabel disponibilidad;
    private javax.swing.JButton existencias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox nombre1;
    private javax.swing.JComboBox nombre2;
    // End of variables declaration//GEN-END:variables
}
